name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Add MongoDB service
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet || echo 'db.runCommand(\"ping\").ok' | mongo localhost:27017/test --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install MongoDB client from official repository
      - name: Install MongoDB client
        run: |
          sudo apt-get update
          # Add MongoDB repository
          wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt-get update
          # Install MongoDB client tools only
          sudo apt-get install -y mongodb-org-shell
          # Verify installation
          mongo --version || echo "Mongo client installation failed, but continuing..."

      # Backend setup
      - name: Install backend dependencies
        run: npm install --prefix backend

      - name: Run backend tests
        run: npm test --prefix backend

      # Frontend setup
      - name: Install frontend dependencies
        run: npm install --prefix frontend

      - name: Install start-server-and-test
        run: npm install --prefix frontend start-server-and-test --save-dev

      # Run UI tests
      - name: Run frontend UI tests
        run: npx start-server-and-test "npm start --prefix frontend" http://localhost:3000 "npx mocha --timeout 120000 'frontend/tests/ui/**/*.test.js'"