name: Donation Campaign CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      # Step 4: Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # Step 5: Run backend tests
      - name: Run backend unit tests
        working-directory: ./backend
        run: npm test

      # Step 6: Run frontend UI tests
      - name: Run frontend UI tests
        working-directory: ./frontend
        run: npm run test:ui
